name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually click a button to build an APK

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Compile Release APK
        working-directory: ./app
        run: flutter build apk --release

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Counterfeit-Detection-App-APK
          path: app/build/app/outputs/flutter-apk/app-release.apk
